clean up, standardize on indentation

diff --git a/mail-to-oncall b/mail-to-oncall
--- a/mail-to-oncall
+++ b/mail-to-oncall
@@ -16,16 +16,15 @@ USAGE_MSG="Usage: `basename $0` -s \"Subject\" fallback.email@example.com"
 
 if [ $# -eq "$NO_ARGS" ]    # Script invoked with no command-line args?
 then
-  echo $USAGE_MSG
-  exit $E_OPTERROR
+    echo $USAGE_MSG; exit $E_OPTERROR
 fi
 
 while getopts "s:" Option
 do
-  case $Option in
-    s     ) SUBJECT=$OPTARG;;
-    *     ) echo "Unimplemented option."; echo $USAGE_MSG; exit $E_OPTERROR;;
-  esac
+    case $Option in
+        s     ) SUBJECT=$OPTARG;;
+        *     ) echo "Unimplemented option."; echo $USAGE_MSG; exit $E_OPTERROR;;
+    esac
 done
 
 shift $(($OPTIND - 1))
@@ -33,8 +32,7 @@ shift $(($OPTIND - 1))
 if [ $# -eq "$NO_ARGS" ] # No argument left after options?
 then
     echo "You must specify a fallback e-mail address!"
-    echo $USAGE_MSG
-    exit $E_OPTERROR
+    echo $USAGE_MSG; exit $E_OPTERROR
 fi
 
 FALLBACK=$1
